name: Deploy Video Processing Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: sa-east-1
  NODE_VERSION: "20"
  PYTHON_VERSION: "3.9"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install function dependencies
        run: |
          # Install production dependencies for each function
          for func_dir in src/functions/*/; do
            if [ -f "$func_dir/package.json" ]; then
              echo "Installing dependencies for $(basename $func_dir)"
              cd "$func_dir"
              npm ci --only=production
              cd - > /dev/null
            fi
          done

      - name: SAM Build
        run: sam build

      - name: Deploy to production
        run: |
          sam deploy \
            --stack-name lancemonos-video-processor \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --region ${{ env.AWS_REGION }}
            --resolve-s3
